name: Android CI - build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Android SDK
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools
          rm cmdline.zip
          # Move to expected path
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/ || true
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest"

      - name: Install unzip (required by Gradle action)
        run: |
          sudo apt-get update -y
          # Install unzip and tar which are required by the Gradle action to unpack distributions
          sudo apt-get install -y unzip tar zip

      - name: Download Gradle and run assembleDebug (direct)
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          GRADLE_VERSION: 8.0.2
        run: |
          set -euo pipefail
          echo "Downloading Gradle $GRADLE_VERSION"
          mkdir -p $HOME/gradle
          wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -O /tmp/gradle.zip
          unzip -q /tmp/gradle.zip -d $HOME/gradle
          export GRADLE_HOME=$HOME/gradle/gradle-${GRADLE_VERSION}
          echo "Gradle home: $GRADLE_HOME"
          ls -la $GRADLE_HOME/bin
          echo "JAVA_HOME=$JAVA_HOME"
          # Run gradle from the unpacked distribution
          $GRADLE_HOME/bin/gradle -v
          $GRADLE_HOME/bin/gradle -Porg.gradle.jvmargs="-Xmx1536m" assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: careercoach-apk
          path: app/build/outputs/apk/debug/*.apk
